<!-- <div id="toc_container"> -->
<h2>Table of Contents</h2>
<ul class="toc_list">
  <a href="#1&nbsp;&nbsp;General-Analysis-Information">1&nbsp;&nbsp;General Analysis Information</a><br>
    <ul>
    <a href="#1.1&nbsp;&nbsp;Project-summary">1.1&nbsp;&nbsp;Project summary</a><br>
    <a href="#1.2&nbsp;&nbsp;Project-directory">1.2&nbsp;&nbsp;Project directory</a><br>
    </ul>
  <a href="#2&nbsp;&nbsp;Manifest-preparation">2&nbsp;&nbsp;Manifest preparation</a><br>
    <ul>
    <a href="#2.1&nbsp;&nbsp;Metadata-overview">2.1&nbsp;&nbsp;Metadata overview</a><br>
    <a href="#2.2&nbsp;&nbsp;Receipt-selection">2.2&nbsp;&nbsp;Receipt selection</a><br>
    <a href="#2.3&nbsp;&nbsp;Output-manifest">2.3&nbsp;&nbsp;Output manifest</a><br>  
    </ul>
  <a href="#3&nbsp;&nbsp;Sequencing-information">3&nbsp;&nbsp;Sequencing information</a><br>
    <ul>
    <a href="#3.1&nbsp;&nbsp;Yaml-parameters">3.1&nbsp;&nbsp;Yaml parameters</a><br>
    <a href="#3.2&nbsp;&nbsp;Pipeline-run">3.2&nbsp;&nbsp;Pipeline run</a><br>
    </ul>
</ul>

In [1]:
%%bash
pip install git+https://github.com/webermarcolivier/statannot

Collecting git+https://github.com/webermarcolivier/statannot
  Cloning https://github.com/webermarcolivier/statannot to c:\users\slsevi~1\appdata\local\temp\pip-req-build-hwwewbvb
Requirement already satisfied (use --upgrade to upgrade): statannot==0.2.2 from git+https://github.com/webermarcolivier/statannot in c:\miniconda\lib\site-packages
Building wheels for collected packages: statannot
  Building wheel for statannot (setup.py): started
  Building wheel for statannot (setup.py): finished with status 'done'
  Created wheel for statannot: filename=statannot-0.2.2-py3-none-any.whl size=11039 sha256=b1b1ef20fbacce0f275a968e5eb70d3a81572f0e336c177910d7dea100d3c6dc
  Stored in directory: C:\Users\SLSEVI~1\AppData\Local\Temp\pip-ephem-wheel-cache-i5xri0rr\wheels\48\70\5d\319e4b342e18b0080826e678683b28bb358cebe0c135651156
Successfully built statannot

  Running command git clone -q https://github.com/webermarcolivier/statannot 'C:\Users\SLSEVI~1\AppData\Local\Temp\pip-req-build-hwwewbvb'

In [2]:
from IPython.display import display
import os.path
%matplotlib inline
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib as mpl
import seaborn as sns
import glob
from scipy import stats
from itertools import combinations
#from skbio.stats.ordination import pcoa
#from skbio import DistanceMatrix
#import os; os.environ['R_HOME'] = "C:\\Miniconda\\lib\\R\\"
import rpy2
sns.set(style="whitegrid")
#import warnings
#warnings.filterwarnings('ignore')
from statannot import add_stat_annotation

<h2 id="1&nbsp;&nbsp;Ge">1&nbsp;&nbsp;General Analysis Information</h2>

<h3 id="1.1&nbsp;&nbsp;Project-summary">1.1&nbsp;&nbsp;Project summary</h3>

AIM 1 consists of a fecal extraction comparison using fresh-frozen fecal material from human donors, and artificial colonies. Samples were extracted using multiple methods, to be examined. The 16S rRNA gene was then sequenced using an Illumina MiSeq from three projects: NP0084-MB4, NP0084-MB5, NP0084-MB6. A summary of the three individual projects is included below:

- NP0084-MB4
- NP0084-MB5
- NP0084-MB6

<h3 id="1.2&nbsp;&nbsp;Project-summary">1.2&nbsp;&nbsp;Project directory</h3>

In [3]:
cgr_proj_dir='/DCEG/Projects/Microbiome/Analysis/NP0084_MB/20200410_2019.1'
proj_dir='/Users/slsevilla/Google Drive/MyDocuments_Current/Education/George Mason University/Dissertation/Data/Aim1/'
img_dir='/Users/slsevilla/Google Drive/MyDocuments_Current/Education/George Mason University/Dissertation/Data/Aim1/output/img'
%cd {proj_dir}

C:\Users\slsevilla\Google Drive\MyDocuments_Current\Education\George Mason University\Dissertation\Data\Aim1

<h2 id="2&nbsp;&nbsp;Manifest-preparation">2&nbsp;&nbsp;Manifest preparation</h3>

<h3 id="2.1&nbsp;&nbsp;Metadata-overview">2.1&nbsp;&nbsp;Metadata overview</h3>

Metadata for the project was included with the metagenomic pipeline requirements.

In [4]:
manifest_path = proj_dir+'manifest//raw_manifest.txt'

manifest = pd.read_csv(glob.glob(manifest_path)[0],sep='\t',index_col=0)
manifest = manifest.dropna(how='all', axis='columns')
manifest.columns = manifest.columns.str.replace(' ', '')

In [5]:
manifest.head()

,Source-PCR-Plate,Run-ID,Project-ID,CGR-Sample-ID,Sample-Type,Sample-Des,Subject-ID,Reciept,Ext-Company,Ext-Kit,Ext-Robotics,Homo-Status,Homo-Method,Homo-Holder
Sample ID,,,,,,,,,,,,,,
SC249358,PC04924_A_01,180112_M01354_0104_000000000-BFN3F,NP0084-MB4,SC249358,Ext_Control,art_col,DZ35322,sFEMB-001-R-002,Qiagen,DSP Virus,QIASymphony,Standard,Vertical,Tubes
SC249363,PC04924_F_01,180112_M01354_0104_000000000-BFN3F,NP0084-MB4,SC249363,Ext_Control,art_col,DZ35322,sFEMB-001-R-002,Qiagen,DSP Virus,QIASymphony,Standard,Vertical,Tubes
SC249366-PC04925-D-01,PC04925_D_01,180112_M03599_0134_000000000-BFD9Y,NP0084-MB4,SC249366,Ext_Control,Ext_Blank,Water,sFEMB-001-R-002,Qiagen,DSP Virus,QIASymphony,Standard,Vertical,Tubes
SC249366-PC07578-D-01,PC07578_D_01,180328_M01354_0106_000000000-BFMHC,NP0084-MB5,SC249366,Ext_Control,Ext_Blank,Water,sFEMB-001-R-002,Qiagen,DSP Virus,QIASymphony,Standard,Vertical,Tubes
SC249367,PC04924_A_02,180112_M01354_0104_000000000-BFN3F,NP0084-MB4,SC249367,Ext_Control,Ext_Blank,Water,sFEMB-001-R-002,Qiagen,DSP Virus,QIASymphony,Standard,Vertical,Tubes

In [6]:
#Print the variables for the metadata
for i in manifest.drop(columns=['Source-PCR-Plate','CGR-Sample-ID']).columns:
    print(i)
    print(*manifest[i].unique(), sep = ", ")  
    print('\n')

Run-ID
180112_M01354_0104_000000000-BFN3F, 180112_M03599_0134_000000000-BFD9Y, 180328_M01354_0106_000000000-BFMHC, 190617_M01354_0118_000000000-CHFG3


Project-ID
NP0084-MB4, NP0084-MB5, NP0084-MB6


Sample-Type
Ext_Control, Study, Seq_Control


Sample-Des
art_col, Ext_Blank, human_1, Robogut, ZymoBiomics, Biocollective, MSA, Seq_Blank


Subject-ID
DZ35322, Water, human_1, DZ35298, D6300, Biocollective, D6310, DZ35316, MSA1000, MSA1001, MSA1002, MSA1003, NTC_Blank, PCR_Blank, D6305, D6306, D6311


Reciept
sFEMB-001-R-002, sFEMB-001-R-003, sFEMB-001-R-004, sFEMB-001-R-005, sFEMB-001-R-006, sFEMB-001-R-007, sFEMB-001-R-008, sFEMB-001-R-009, sFEMB-001-R-010, sFEMB-001-R-011, sFEMB-001-R-012, sFEMB-001-R-013, sFEMB-001-R-014, sFEMB-001-R-015, sFEMB-001-R-016, sFEMB-001-R-017, sFEMB-001-R-034, sFEMB-001-R-037, sFEMB-001-R-038, sFEMB-001-R-039, sFEMB-001-R-040, sFEMB-001-R-041, sFEMB-001-R-042, sFEMB-001-R-043, sFEMB-001-R-044, sFEMB-001-R-045, sFEMB-001-R-046, sFEMB-001-R-047, sFEMB-001-R-048, sFEMB-001-R-049, sFEMB-001-R-050, sFEMB-001-R-051, sFEMB-001-R-052, sFEMB-001-R-053, sFEMB-001-R-054, sFEMB-001-R-055, nan


Ext-Company
Qiagen, ZymoResearch, ThermoFisher, nan


Ext-Kit
DSP Virus, 96 MagBead DNA Extraction Kit, MagAttract PowerSoil DNA Kit, MagAttract PowerMicrobiome Kit, QIAamp with Modifications, DNeasy PowerSoil Pro kit, MagMax Microbiome Ultra Kit, nan


Ext-Robotics
QIASymphony, None, KingFisher, QIACube HT, nan


Homo-Status
Standard, Discard, Residual, Altered, Horizontal, SPEX, Covaris, nan


Homo-Method
Vertical, Plate Adaptor, TissueLyzer, Horizontal, SPEX, AFA, nan


Homo-Holder
Tubes, Plate, nan

In [7]:
manifest["Run-ID"].unique()

array(['180112_M01354_0104_000000000-BFN3F',
       '180112_M03599_0134_000000000-BFD9Y',
       '180328_M01354_0106_000000000-BFMHC',
       '190617_M01354_0118_000000000-CHFG3'], dtype=object)

In [8]:
#Rename run ids, remove well location
manifest.replace({"180112_M01354_0104_000000000-BFN3F":"Run1","180112_M03599_0134_000000000-BFD9Y":"Run2",
                 "180328_M01354_0106_000000000-BFMHC":"Run3","190617_M01354_0118_000000000-CHFG3":"Run4"},inplace=True)
manifest.replace({r'_._..': r''}, inplace=True, regex=True)
manifest.head()

,Source-PCR-Plate,Run-ID,Project-ID,CGR-Sample-ID,Sample-Type,Sample-Des,Subject-ID,Reciept,Ext-Company,Ext-Kit,Ext-Robotics,Homo-Status,Homo-Method,Homo-Holder
Sample ID,,,,,,,,,,,,,,
SC249358,PC04924,Run1,NP0084-MB4,SC249358,Ext_Control,art_col,DZ35322,sFEMB-001-R-002,Qiagen,DSP Virus,QIASymphony,Standard,Vertical,Tubes
SC249363,PC04924,Run1,NP0084-MB4,SC249363,Ext_Control,art_col,DZ35322,sFEMB-001-R-002,Qiagen,DSP Virus,QIASymphony,Standard,Vertical,Tubes
SC249366-PC04925-D-01,PC04925,Run2,NP0084-MB4,SC249366,Ext_Control,Ext_Blank,Water,sFEMB-001-R-002,Qiagen,DSP Virus,QIASymphony,Standard,Vertical,Tubes
SC249366-PC07578-D-01,PC07578,Run3,NP0084-MB5,SC249366,Ext_Control,Ext_Blank,Water,sFEMB-001-R-002,Qiagen,DSP Virus,QIASymphony,Standard,Vertical,Tubes
SC249367,PC04924,Run1,NP0084-MB4,SC249367,Ext_Control,Ext_Blank,Water,sFEMB-001-R-002,Qiagen,DSP Virus,QIASymphony,Standard,Vertical,Tubes

<h3 id="2.2&nbsp;&nbsp;Sample-selection">2.2&nbsp;&nbsp;Sample selection</h3>

There were a number of receipts included in this manifest, that will not be used. Additionally there is one sample type (Sample.Des=Biocollective) that will also not be used.

<h4 id="2.2.1&nbsp;&nbsp;Receipts-removed">2.2.1&nbsp;&nbsp;Receipts removed</h4>
Receipts were removed from the project for the following reasons:

- Receipts that failed sequencing: R-01*, R-04, R-012
- Receipts that were cancelled: R-23 to R-25*
- Receipts that contained residuals: R-13, R-14, R-17

*Not included in sequencing project, but found in LIMS

In [9]:
def sort_list (m,col):
    sort_list = [x for x in m[col].unique() if str(x) != 'nan']
    sort_list.sort()
    return sort_list

In [10]:
print ("Receipt", "Ext Kit", "Homogenization Method", sep = " - ")
for i in sort_list(manifest,'Reciept'):
    temp = manifest[(manifest['Reciept'] == i)]
    col2 = temp['Ext-Kit'].unique()
    col3 = temp['Homo-Status'].unique()
    print (i, col2[0], col3[0],sep=" - ")

Receipt - Ext Kit - Homogenization Method
sFEMB-001-R-002 - DSP Virus - Standard
sFEMB-001-R-003 - 96 MagBead DNA Extraction Kit - Standard
sFEMB-001-R-004 - 96 MagBead DNA Extraction Kit - Discard
sFEMB-001-R-005 - MagAttract PowerSoil DNA Kit - Standard
sFEMB-001-R-006 - MagAttract PowerSoil DNA Kit - Standard
sFEMB-001-R-007 - MagAttract PowerMicrobiome Kit - Standard
sFEMB-001-R-008 - MagAttract PowerMicrobiome Kit - Standard
sFEMB-001-R-009 - QIAamp with Modifications - Standard
sFEMB-001-R-010 - QIAamp with Modifications - Standard
sFEMB-001-R-011 - DSP Virus - Standard
sFEMB-001-R-012 - 96 MagBead DNA Extraction Kit - Discard
sFEMB-001-R-013 - MagAttract PowerSoil DNA Kit - Residual
sFEMB-001-R-014 - MagAttract PowerMicrobiome Kit - Residual
sFEMB-001-R-015 - 96 MagBead DNA Extraction Kit - Standard
sFEMB-001-R-016 - 96 MagBead DNA Extraction Kit - Standard
sFEMB-001-R-017 - 96 MagBead DNA Extraction Kit - Residual
sFEMB-001-R-034 - DNeasy PowerSoil Pro kit - Altered
sFEMB-001-R-037 - MagAttract PowerSoil DNA Kit - Standard
sFEMB-001-R-038 - MagAttract PowerMicrobiome Kit - Standard
sFEMB-001-R-039 - DNeasy PowerSoil Pro kit - Standard
sFEMB-001-R-040 - MagAttract PowerSoil DNA Kit - Standard
sFEMB-001-R-041 - 96 MagBead DNA Extraction Kit - Standard
sFEMB-001-R-042 - MagMax Microbiome Ultra Kit - Standard
sFEMB-001-R-043 - DNeasy PowerSoil Pro kit - Horizontal
sFEMB-001-R-044 - 96 MagBead DNA Extraction Kit - Horizontal
sFEMB-001-R-045 - MagAttract PowerSoil DNA Kit - SPEX
sFEMB-001-R-046 - MagAttract PowerMicrobiome Kit - SPEX
sFEMB-001-R-047 - DNeasy PowerSoil Pro kit - SPEX
sFEMB-001-R-048 - MagAttract PowerSoil DNA Kit - SPEX
sFEMB-001-R-049 - 96 MagBead DNA Extraction Kit - SPEX
sFEMB-001-R-050 - MagMax Microbiome Ultra Kit - SPEX
sFEMB-001-R-051 - MagAttract PowerSoil DNA Kit - Covaris
sFEMB-001-R-052 - MagAttract PowerMicrobiome Kit - Covaris
sFEMB-001-R-053 - DNeasy PowerSoil Pro kit - Covaris
sFEMB-001-R-054 - 96 MagBead DNA Extraction Kit - Covaris
sFEMB-001-R-055 - MagMax Microbiome Ultra Kit - Covaris

In [11]:
m_rec = manifest.copy()

recp_num = ['04','12','13','14','17']
drop_recp = []

for i in recp_num:
    drop_recp.append("sFEMB-001-R-0" + i)

m_rec = manifest[~manifest.Reciept.isin(drop_recp)]
m_rec_rm = manifest[manifest.Reciept.isin(drop_recp)]
m_rec.shape

(424, 14)

<h4 id="2.2.2&nbsp;&nbsp;Samples-removed">2.2.2&nbsp;&nbsp;Samples removed</h4>

In [12]:
m_nonbio = m_rec[m_rec['Sample-Des']!="Biocollective"]
m_nonbio.shape

(389, 14)

In [13]:
def metacount_all(df_in):
    #Print the counts for all of the metadata
    m = df_in.drop(columns=['ExternalID','Project-ID','ExtractionBatchID'],errors='ignore')

    for i in m.columns:
        display(m[i].value_counts().rename_axis(i).to_frame('Number of samples'))

<h3 id="2.3&nbsp;&nbsp;Project-sample-metadata">2.3&nbsp;&nbsp;Project sample metadata</h3>

In [14]:
metacount_all(m_nonbio)

                  Number of samples
Source-PCR-Plate
PC04924                          85
PC04925                          79
PC22190                          76
PC22192                          75
PC07578                          74

        Number of samples
Run-ID
Run4                  151
Run1                   85
Run2                   79
Run3                   74

               Number of samples
CGR-Sample-ID
SC249448                       4
SC253199                       3
SC249391                       3
SC249429                       3
SC249411                       3
...                          ...
SC553063                       1
SC553032                       1
SC553016                       1
SC553039                       1
SC253844                       1

[298 rows x 1 columns]

             Number of samples
Sample-Type
Study                      180
Ext_Control                167
Seq_Control                 42

             Number of samples
Sample-Des
human_1                    131
ZymoBiomics                 91
Ext_Blank                   58
Robogut                     49
art_col                     30
MSA                         20
Seq_Blank                   10

            Number of samples
Subject-ID
human_1                   131
Water                      58
D6300                      57
DZ35298                    49
DZ35322                    25
D6310                      22
MSA1001                     5
DZ35316                     5
PCR_Blank                   5
MSA1002                     5
D6305                       5
MSA1003                     5
MSA1000                     5
NTC_Blank                   5
D6306                       5
D6311                       2

                 Number of samples
Reciept
sFEMB-001-R-007                 26
sFEMB-001-R-002                 24
sFEMB-001-R-006                 23
sFEMB-001-R-008                 22
sFEMB-001-R-011                 21
sFEMB-001-R-010                 21
sFEMB-001-R-005                 21
sFEMB-001-R-009                 18
sFEMB-001-R-003                 18
sFEMB-001-R-034                 16
sFEMB-001-R-052                 14
sFEMB-001-R-016                 10
sFEMB-001-R-015                 10
sFEMB-001-R-039                 10
sFEMB-001-R-037                  9
sFEMB-001-R-042                  9
sFEMB-001-R-041                  9
sFEMB-001-R-038                  9
sFEMB-001-R-040                  9
sFEMB-001-R-047                  4
sFEMB-001-R-048                  4
sFEMB-001-R-054                  4
sFEMB-001-R-043                  4
sFEMB-001-R-045                  4
sFEMB-001-R-050                  4
sFEMB-001-R-046                  4
sFEMB-001-R-053                  4
sFEMB-001-R-051                  4
sFEMB-001-R-055                  4
sFEMB-001-R-044                  4
sFEMB-001-R-049                  4

              Number of samples
Ext-Company
Qiagen                      271
ZymoResearch                 59
ThermoFisher                 17

                                Number of samples
Ext-Kit
MagAttract PowerMicrobiome Kit                 75
MagAttract PowerSoil DNA Kit                   74
96 MagBead DNA Extraction Kit                  59
DSP Virus                                      45
QIAamp with Modifications                      39
DNeasy PowerSoil Pro kit                       38
MagMax Microbiome Ultra Kit                    17

              Number of samples
Ext-Robotics
KingFisher                  166
None                        120
QIASymphony                  45
QIACube HT                   16

             Number of samples
Homo-Status
Standard                   269
Covaris                     30
SPEX                        24
Altered                     16
Horizontal                   8

               Number of samples
Homo-Method
Vertical                     139
TissueLyzer                  128
AFA                           30
SPEX                          24
Plate Adaptor                 18
Horizontal                     8

             Number of samples
Homo-Holder
Tubes                      181
Plate                      166

In [15]:
def metacount_run_sub(df_in):
    tmp = df_in[['Run-ID','Subject-ID']].copy()
    tmp = tmp.groupby(['Run-ID','Subject-ID'])
    display(tmp.size().to_frame('Subject-ID').join(tmp.apply(list).apply(pd.Series)))

In [16]:
metacount_run_sub(m_nonbio)

                   Subject-ID       0           1
Run-ID Subject-ID
Run1   D6300               14  Run-ID  Subject-ID
       D6305                1  Run-ID  Subject-ID
       D6306                1  Run-ID  Subject-ID
       DZ35298             14  Run-ID  Subject-ID
       DZ35322             14  Run-ID  Subject-ID
       MSA1000              1  Run-ID  Subject-ID
       MSA1001              1  Run-ID  Subject-ID
       MSA1002              1  Run-ID  Subject-ID
       MSA1003              1  Run-ID  Subject-ID
       NTC_Blank            1  Run-ID  Subject-ID
       PCR_Blank            1  Run-ID  Subject-ID
       Water                7  Run-ID  Subject-ID
       human_1             28  Run-ID  Subject-ID
Run2   D6300                8  Run-ID  Subject-ID
       D6305                1  Run-ID  Subject-ID
       D6306                1  Run-ID  Subject-ID
       DZ35298             12  Run-ID  Subject-ID
       DZ35322              4  Run-ID  Subject-ID
       MSA1000              1  Run-ID  Subject-ID
       MSA1001              1  Run-ID  Subject-ID
       MSA1002              1  Run-ID  Subject-ID
       MSA1003              1  Run-ID  Subject-ID
       NTC_Blank            1  Run-ID  Subject-ID
       PCR_Blank            1  Run-ID  Subject-ID
       Water                8  Run-ID  Subject-ID
       human_1             39  Run-ID  Subject-ID
Run3   D6300               14  Run-ID  Subject-ID
       D6305                1  Run-ID  Subject-ID
       D6306                1  Run-ID  Subject-ID
       DZ35298             16  Run-ID  Subject-ID
       DZ35322              5  Run-ID  Subject-ID
       MSA1000              1  Run-ID  Subject-ID
       MSA1001              1  Run-ID  Subject-ID
       MSA1002              1  Run-ID  Subject-ID
       MSA1003              1  Run-ID  Subject-ID
       NTC_Blank            1  Run-ID  Subject-ID
       PCR_Blank            1  Run-ID  Subject-ID
       Water                7  Run-ID  Subject-ID
       human_1             24  Run-ID  Subject-ID
Run4   D6300               21  Run-ID  Subject-ID
       D6305                2  Run-ID  Subject-ID
       D6306                2  Run-ID  Subject-ID
       D6310               22  Run-ID  Subject-ID
       D6311                2  Run-ID  Subject-ID
       DZ35298              7  Run-ID  Subject-ID
       DZ35316              5  Run-ID  Subject-ID
       DZ35322              2  Run-ID  Subject-ID
       MSA1000              2  Run-ID  Subject-ID
       MSA1001              2  Run-ID  Subject-ID
       MSA1002              2  Run-ID  Subject-ID
       MSA1003              2  Run-ID  Subject-ID
       NTC_Blank            2  Run-ID  Subject-ID
       PCR_Blank            2  Run-ID  Subject-ID
       Water               36  Run-ID  Subject-ID
       human_1             40  Run-ID  Subject-ID

<h3 id="2.4&nbsp;&nbsp;Output-manifest">2.4&nbsp;&nbsp;Output manifest</h3>

Sample ID's need to be renamed to include "-", to match the FastQ folder paths. The cleaned manifest was saved used for sequencing.

In [17]:
%cd {proj_dir}

C:\Users\slsevilla\Google Drive\MyDocuments_Current\Education\George Mason University\Dissertation\Data\Aim1

In [18]:
m_nonbio.reset_index(inplace = True)
m_nonbio['Sample ID'].str.replace('_','-')

m_nonbio.to_csv(r'manifest/m_rec.txt',header = m_nonbio.columns,index = False, sep='\t')
m_nonbio.to_csv(r'manifest/m_rec_rm.txt',header = m_nonbio.columns,index = False, sep='\t')
m_nonbio.set_index('Sample ID',inplace=True)

m_save=m_nonbio.copy()
m_save.shape

(389, 14)

<h2 id="3&nbsp;&nbsp;Sequencing-information">3&nbsp;&nbsp;Sequencing information</h2>

<h3 id="3.1&nbsp;&nbsp;Yaml-parameters">3.1&nbsp;&nbsp;Yaml parameters</h3>

All project samples were processed using the following parameters:

In [19]:
%cd manifest
!cat *.yml

C:\Users\slsevilla\Google Drive\MyDocuments_Current\Education\George Mason University\Dissertation\Data\Aim1\manifest
# CGR QIIME2 pipeline for microbiome analysis.
#
# AUTHORS:
#     S. Sevilla Chill
#     W. Zhou
#     B. Ballew

## Manifest
metadata_manifest: '/DCEG/Projects/Microbiome/Analysis/Project_NP0084_MB/20200410_2019.1/manifest.txt'

## Directories
out_dir: '/DCEG/Projects/Microbiome/Analysis/Project_NP0084_MB/20200410_2019.1'
exec_dir: '/DCEG/CGF/Bioinformatics/Production/Sam/dev/QIIME_pipeline'
fastq_abs_path: '/DCEG/CGF/Sequencing/Illumina/MiSeq/PostRun_Analysis/Data'  # internal runs only
temp_dir: '/DCEG/CGF/Bioinformatics/Production/Sam/scratch'

## Run type
data_source: 'internal'  # 'external' or 'internal' (to CGR)
  # for external data, require an additional metadata columns called "fq1" and "fq2" with full path and file names for R1 and R2 fastqs (do they need to be zipped?)

## QIIME version
qiime2_version: '2019.1'  # 2017.11 or 2019.1

## Analysis parameters
denoise_method: 'dada2' # not yet implemented
dada2_denoise:
  trim_left_forward: 0
  trim_left_reverse: 0
  truncate_length_forward: 0
  truncate_length_reverse: 0
phred_score: 33
demux_param: 'paired_end_demux'
input_type: 'SampleData[PairedEndSequencesWithQuality]'
filt_param: 1
sampling_depth: 10000
max_depth: 54000
classify_method: 'classify-sklearn'
reference_db:  # change based on qiime version
- '/DCEG/CGF/Bioinformatics/Production/Bari/refDatabases/scikit_0.20.2_q2_2019.1/gg-13-8-99-nb-classifier.qza'
- '/DCEG/CGF/Bioinformatics/Production/Bari/refDatabases/scikit_0.20.2_q2_2019.1/silva-132-99-nb-classifier.qza'

## Cluster submission parameters
cluster_mode: 'qsub -q long.q -V -j y -S /bin/bash -o /DCEG/Projects/Microbiome/Analysis/Project_NP0084_MB/20200410_2019.1/logs -pe by_node {threads}'  # options are 'qsub/sbatch/etc ...', 'local', 'dryrun', 'unlock'
  # SGE example:    qsub -q myqueue.q -V -j y -S /bin/bash -o /path/to/project/directory/logs/ -pe by_node {threads}
  # slurm example:  sbatch --mem=64g --time=24:00:00 --output=/path/to/project/directory/logs/slurm-%j.out --cpus-per-task={threads}
num_jobs: 10
latency: 60

<h3 id="3.2&nbsp;&nbsp;Pipeline-run">3.2&nbsp;&nbsp;Pipeline run</h3>

In [20]:
#qlogin -q interactive.q
#cd /DCEG/Projects/Microbiome/Analysis/NP0084_MB/20200410_2019.1
#sh run_pipeline.sh

In [37]:
m_save['Ext-Kit'].unique()

array(['DSP Virus', '96 MagBead DNA Extraction Kit',
       'MagAttract PowerSoil DNA Kit', 'MagAttract PowerMicrobiome Kit',
       'QIAamp with Modifications', 'DNeasy PowerSoil Pro kit',
       'MagMax Microbiome Ultra Kit', nan], dtype=object)